name: "Deploy Packages"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Branch to deploy'
        required: true
        default: 'master'
      deploy_to_myget:
        description: 'Deploy packages to MyGet?'
        required: true
        default: true
      deploy_to_tizen:
        description: 'Submit changes to Tizen?'
        required: true
        default: true

  # schedule:
  # - cron: "0 16 * * *"

env:
  TARGET_BRANCH: ${{ github.event.inputs.target }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ env.TARGET_BRANCH }}
        fetch-depth: 0

    - name: Get Branch Metadata
      id: metadata
      uses: TizenAPI/tizenfx-build-actions/branch-metadata@master
      with:
        ref: ${{ env.TARGET_BRANCH }}

    - name: Get Version
      id: version
      env:
        VERSION_PREFIX: ${{ steps.metadata.outputs.version-prefix }}
      run: |
        VERSION=$VERSION_PREFIX.$((10000+$(git rev-list --count HEAD)))
        echo VERSION=$VERSION
        echo "::set-output name=version::$VERSION"

    - name: Build
      env:
        VERSION: ${{ steps.version.outputs.version }}
      run: |
        ./build.sh full
        ./build.sh pack $VERSION

    - name: Deploy NuGet packages to MyGet
      if: github.event.inputs.deploy_to_myget == 'true'
      env:
        NUGET_SOURCE: https://tizen.myget.org/F/dotnet-test/api/v2/package
        APIKEY: ${{ secrets.MYGET_APIKEY }}
      run: |
        dotnet nuget push Artifacts/*.nupkg -k $APIKEY -s $NUGET_SOURCE -t 3000

    - name: Test
      run: |
        echo "${{ steps.version.outputs.version }}"

