name: "Deploy Packages"

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Branch to Deploy'
        required: true
        default: 'master'

  # schedule:
  # - cron: "0 16 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        echo "${{ github.event.inputs.target }}"

